### ISSUE TITLE
Resolved: Dugway / FFI installation problem

### ISSUE THREAD

**Issue by EmagineEngine** [bigcartel/dugway#207]
## Update 

This issue has been resolved by finding the correct version of FFI to install. Below is a description of the problem and its solution.

## Problem

At least for me, in 2024 Dugway would not install due to error messages. It behaved as if Dugway needed first to be updated to Ruby 3.x.

The core problem was that the version of the FFI gem that it tries to install is not compatible with rubygems-update, for a 2.x version of Ruby. _The solution was to find the correct version of the FFI gem._

Here is system info:  

- OS: Ubuntu 24.04.1 LTS
- Ruby installation through rbenv
- Attempted Ruby versions: 2.7.8, 2.5.8, 2.3.8 in the "local" directory, where I am installing Dugway

On Ruby 2.7.8 and 2.5.8, the installation progressed along just fine _until_ it reached the FFI installation. (Ruby 2.3.8 stops even sooner with an error on installing execjs.)

Since FFI installation is where it stops, below  is an error sequence when I tried to install FFI on its own. I had assumed the correct version of FFI to use was 1.17.1 because the error message says to try installing it:

```BASH
LocalUser:~/dev/dugway$ gem install ffi -v 1.17.1
ERROR:  Error installing ffi:
    The last version of ffi (= 1.17.1) to support your Ruby & RubyGems was 1.17.1. Try installing it with `gem install ffi -v 1.17.1` and then running the current command again
    ffi requires RubyGems version >= 3.3.22. The current RubyGems version is 3.1.6. Try 'gem update --system' to update RubyGems itself.
LocalUser:~/dev/dugway$ gem update --system
Updating rubygems-update
ERROR:  Error installing rubygems-update:
    There are no versions of rubygems-update (= 3.6.2) compatible with your Ruby & RubyGems
    rubygems-update requires Ruby version >= 3.1.0. The current ruby version is 2.7.8.225.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass
```

## How Resolved

I explored the rubygems page for FFI and found a version that would work with Ruby version >= 2.3 (that is, version 1.15.5), and installed it like so:

`gem install ffi -v 1.15.5`

Then I tried the installation of dugway:

`gem install dugway`

And installation completed without any difficulty.
